name: DS-CICD
on: 
  push:
    branches: 
      - master

jobs:
    build:
        name: DS-BUILD
        
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              run: npm install
            - name: Lint
              run: npm run lint
